; PHP production RT05 TAKEDA
expose_php = Off
display_errors = Off
log_errors = On
memory_limit = 256M
upload_max_filesize = 13M
post_max_size = 70M
max_file_uploads = 6
opcache.enable = 1
opcache.validate_timestamps = 0
opcache.memory_consumption = 128
date.timezone = UTC
